databases:
  - name: gestao-moradias-db
    databaseName: gestao_moradias_db
    user: gestao_moradias_user
    plan: free

services:
  - type: web
    name: gestao-moradias-backend
    plan: free
    runtime: docker
    repo: https://github.com/juniorgalindo1990/gestao-moradias
    autoDeploy: true
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: gestao-moradias-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gestao-moradias-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: gestao-moradias-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: gestao-moradias-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: gestao-moradias-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "https://gestao-moradias-frontend.onrender.com"

  - type: web
    name: gestao-moradias-frontend
    plan: free
    runtime: docker
    repo: https://github.com/juniorgalindo1990/gestao-moradias
    autoDeploy: true
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NG_APP_API_URL
        fromService:
          type: web
          name: gestao-moradias-backend
          property: url