databases:
  - name: gestao-moradias-db
    databaseName: gestao_moradias_db
    user: gestao_moradias_user
    plan: free

services:
  - type: web
    name: gestao-moradias-backend
    plan: free
    runtime: docker
    repo: https://github.com/juniorgalindo1990/gestao-moradias
    autoDeploy: true
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "https://placeholder.com"

  - type: web
    name: gestao-moradias-frontend
    plan: free
    runtime: docker
    repo: https://github.com/juniorgalindo1990/gestao-moradias
    autoDeploy: true
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NG_APP_API_URL
        value: "https://placeholder.com"